"""Meeting Summary v2 dashboard layout.

Canvas: 1260 × 800. Coordinates are derived from the user's screenshot of the
new design — no Figma node available for this revision, so values were eyeballed
against the screenshot's relative proportions and then tuned during preview.

Layout structure::

    +-- Header ---------------------------------------------------+
    | [back]  Meeting Summary                                     |
    +-- Meta card -----------------------------------------------+
    | [file] Title                                  [Export][Share]
    |        date  · duration                                    |
    |        [participants chip][recorded chip]                  |
    +-- Sidebar ------+-- Content area ------------------------+
    | Overview        | (varies per tab)                       |
    | Key Points      |                                        |
    | Action Items    |                                        |
    | Decisions Made  |                                        |
    | Participants    |                                        |
    | Transcript      |                                        |
    | ...             |                                        |
    | [Play Recording]|                                        |
    +-----------------+----------------------------------------+
    |  Created: ...                          Generated by AI   |
    +------------------------------------------------------------+
"""

from __future__ import annotations

from typing import TypedDict


class Box(TypedDict):
    x: float
    y_top: float
    w: float
    h: float


CANVAS_W = 1260.0
CANVAS_H = 800.0


def canvas_box(lx: float, ly: float, lw: float, lh: float) -> Box:
    return dict(
        x=lx / CANVAS_W,
        y_top=ly / CANVAS_H,
        w=lw / CANVAS_W,
        h=lh / CANVAS_H,
    )


# ── Header ───────────────────────────────────────────────────────────────
BACK_BTN = canvas_box(28.0, 22.0, 60.0, 60.0)
PAGE_TITLE = canvas_box(104.0, 30.0, 360.0, 42.0)
PAGE_TITLE_FS_RATIO = 28.0 / CANVAS_H


# ── Meta card ────────────────────────────────────────────────────────────
META_CARD = canvas_box(28.0, 92.0, 1204.0, 116.0)
_M_X = 28.0
_M_Y = 92.0

META_FILE_ICON = canvas_box(_M_X + 18.0, _M_Y + 18.0, 80.0, 80.0)
META_TITLE = canvas_box(_M_X + 112.0, _M_Y + 12.0, 660.0, 36.0)
META_DATE = canvas_box(_M_X + 112.0, _M_Y + 48.0, 500.0, 28.0)
META_PARTICIPANTS = canvas_box(_M_X + 112.0, _M_Y + 82.0, 140.0, 28.0)
META_RECORDED = canvas_box(_M_X + 262.0, _M_Y + 82.0, 110.0, 28.0)
META_EXPORT = canvas_box(_M_X + 880.0, _M_Y + 30.0, 140.0, 52.0)
META_SHARE = canvas_box(_M_X + 1034.0, _M_Y + 30.0, 140.0, 52.0)

META_TITLE_FS_RATIO = 20.0 / CANVAS_H
META_DATE_FS_RATIO = 15.0 / CANVAS_H


# ── Sidebar ──────────────────────────────────────────────────────────────
SIDEBAR_CARD = canvas_box(28.0, 224.0, 224.0, 520.0)
_S_X = 28.0
_S_Y = 224.0

# Tab geometry (relative to canvas; each tab is a separate Box).
_TAB_X_OFFSET = 14.0
_TAB_Y_OFFSET = 16.0
_TAB_W = 196.0
_TAB_H = 44.0
_TAB_GAP = 6.0


def _tab(i: int) -> Box:
    return canvas_box(
        _S_X + _TAB_X_OFFSET,
        _S_Y + _TAB_Y_OFFSET + i * (_TAB_H + _TAB_GAP),
        _TAB_W,
        _TAB_H,
    )


TAB_OVERVIEW = _tab(0)
TAB_ACTION_ITEMS = _tab(1)
TAB_PARTICIPANTS = _tab(2)
TAB_TRANSCRIPT = _tab(3)
TAB_FS_RATIO = 15.0 / CANVAS_H

# Play recording pill — sits at the bottom of the sidebar with a 14px gutter
# from the sidebar's bottom edge.
PLAY_RECORDING = canvas_box(
    _S_X + _TAB_X_OFFSET,
    _S_Y + 520.0 - 14.0 - 56.0,
    _TAB_W,
    56.0,
)
PLAY_RECORDING_FS_RATIO = 15.0 / CANVAS_H


# ── Content area (everything to the right of the sidebar) ────────────────
CONTENT_AREA = canvas_box(264.0, 224.0, 968.0, 520.0)
_C_X = 264.0
_C_Y = 224.0
_C_W = 968.0
_C_H = 520.0


# Overview tab — three rows:
#   Row 1: AI Summary card                 (full width, 140 tall)
#   Row 2: Key Topics card                 (full width, 158 tall — needs
#                                           enough room to vertically separate
#                                           topic names from progress bars)
#   Row 3: Action Items + Decisions Made   (side by side, fills remainder)
OV_GAP = 12.0
OV_AI_CARD = canvas_box(_C_X, _C_Y, _C_W, 140.0)

OV_KEY_CARD = canvas_box(_C_X, _C_Y + 140.0 + OV_GAP, _C_W, 158.0)

_R3_Y = _C_Y + 140.0 + OV_GAP + 158.0 + OV_GAP
_R3_H = _C_H - (_R3_Y - _C_Y)
_R3_HALF_W = (_C_W - OV_GAP) / 2
OV_ACTIONS_CARD = canvas_box(_C_X, _R3_Y, _R3_HALF_W, _R3_H)
OV_DECISIONS_CARD = canvas_box(_C_X + _R3_HALF_W + OV_GAP, _R3_Y, _R3_HALF_W, _R3_H)


# Full-tab cards (one card spanning the whole content area).
FULL_TAB_CARD = canvas_box(_C_X, _C_Y, _C_W, _C_H)


# ── Footer ───────────────────────────────────────────────────────────────
FOOTER_LEFT = canvas_box(36.0, 760.0, 500.0, 28.0)
FOOTER_RIGHT = canvas_box(724.0, 760.0, 500.0, 28.0)
FOOTER_FS_RATIO = 12.0 / CANVAS_H


# ── Typography ───────────────────────────────────────────────────────────
SECTION_TITLE_FS_RATIO = 13.0 / CANVAS_H   # section header label
SECTION_BODY_FS_RATIO = 15.0 / CANVAS_H    # row text, summary body
SECTION_HINT_FS_RATIO = 12.0 / CANVAS_H    # helper/date text


# ── Colours (sampled from the screenshot) ────────────────────────────────
BG_RGB = (242, 242, 247)  # #F2F2F7

# Cards
CARD_FILL = (1.0, 1.0, 1.0, 1.0)
CARD_BORDER = (229 / 255, 229 / 255, 234 / 255, 1.0)
CARD_RADIUS = 16.0

# Sidebar
SIDEBAR_FILL = (1.0, 1.0, 1.0, 1.0)
SIDEBAR_BORDER = (229 / 255, 229 / 255, 234 / 255, 1.0)

# Active tab pill
TAB_ACTIVE_FILL = (0.0, 122 / 255, 1.0, 0.10)
TAB_ACTIVE_BORDER = (0.0, 122 / 255, 1.0, 0.35)
TAB_ACTIVE_RADIUS = 10.0

# Play recording pill
PLAY_FILL = (1.0, 1.0, 1.0, 1.0)
PLAY_BORDER = (209 / 255, 209 / 255, 214 / 255, 1.0)
PLAY_RADIUS = 12.0

# Progress bar
PROG_TRACK_FILL = (229 / 255, 229 / 255, 234 / 255, 1.0)
PROG_FILL = (0.0, 122 / 255, 1.0, 1.0)
PROG_RADIUS = 4.0

# CTA accent button (used when a tab needs a "View all" link)
ACCENT_BLUE = (0.0, 122 / 255, 1.0, 1.0)

# Text
COL_WHITE = (28 / 255, 28 / 255, 30 / 255, 1.0)
COL_MUTED = (28 / 255, 28 / 255, 30 / 255, 1.0)
COL_HINT = (142 / 255, 142 / 255, 147 / 255, 1.0)
COL_ACCENT = ACCENT_BLUE


def scaled_canvas(screen_w: float, screen_h: float) -> tuple[float, float]:
    if screen_w <= 0 or screen_h <= 0:
        return CANVAS_W, CANVAS_H
    scale = min(screen_w / CANVAS_W, screen_h / CANVAS_H)
    return CANVAS_W * scale, CANVAS_H * scale


def kivy_hints(box: Box) -> dict:
    return {
        "size_hint": (box["w"], box["h"]),
        "pos_hint": {"x": box["x"], "y": 1.0 - box["y_top"] - box["h"]},
    }


_FONT_MIN_PX = 10
_FONT_MAX_PX = 96


def font_px(fs_ratio: float, canvas_height: float) -> int:
    raw = round(fs_ratio * canvas_height)
    return max(_FONT_MIN_PX, min(_FONT_MAX_PX, raw))


# ── Sub-card slots inside a single tab content area ──────────────────────
# Used by Key Points / Action Items / Decisions / Participants / Transcript
# full views. The content sits inside FULL_TAB_CARD with consistent padding.

CONTENT_PAD_X = 28.0    # horizontal padding from card edge
CONTENT_PAD_TOP = 24.0  # top padding from card edge
CONTENT_PAD_BOT = 24.0  # bottom padding from card edge

# Header row inside a full card (icon + section title).
def content_header(card: Box, icon_w: float = 36.0, title_w: float = 320.0) -> tuple[Box, Box]:
    x_canvas = card["x"] * CANVAS_W
    y_canvas = card["y_top"] * CANVAS_H
    icon = canvas_box(x_canvas + CONTENT_PAD_X, y_canvas + CONTENT_PAD_TOP, icon_w, icon_w)
    title = canvas_box(x_canvas + CONTENT_PAD_X + icon_w + 12.0, y_canvas + CONTENT_PAD_TOP + 2.0, title_w, icon_w - 4.0)
    return icon, title
